### ISSUE TITLE
add prerequisite libraries check in cmake

### ISSUE THREAD

**Issue by ponyatov** [grwlf/xkb-switch#29]
It would be great to check required -dev libraries installed in the system

- libxkbfile-dev

**Comment by grwlf** [comment]
I'm not a CMake expert, so I prefer to wait for someone to send me a PR implementing this..

**Comment by grwlf** [comment]
Do you think I can remove the following lines from the README?

```
Make sure you have package *libxkbfile-dev* (or *libxkbfile-devel* for Fedora)
installed.
```

**Comment by alexandersolovyov** [comment]
> Do you think I can remove the following lines from the README?
> 
> ```
> Make sure you have package *libxkbfile-dev* (or *libxkbfile-devel* for Fedora)
> installed.
> ```

I think it's better to leave it there, because this package is usually not installed by default on most systems. You may change it to `build will fail if You have no libxkbfile-dev installed`, or leave it as-is.
