### ISSUE TITLE
man broken by default with recent version

### ISSUE THREAD

**Issue by orestisfl** [grwlf/xkb-switch#48]
Hey, this was initially reported [here](https://aur.archlinux.org/packages/xkb-switch/) but I see that you recently changed something in your CMakeLists.txt regarding `man`. Specifically, after installing I get this error:

```shell
$ man 1 xkb-switch
man: warning: /usr/share/man/man1/xkb-switch.1.xz.gz: ignoring bogus filename
No manual entry for xkb-switch in section 1
```

I follow a very simple installation process: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xkb-switch

**Comment by grwlf** [comment]
Hi. Yep I also see this error, thanks. This could be due to .xz. compression. As a workaround, you could disable it by commenting-out corresponding line in `CMakeLists.txt`. May be we shouldn't use it by default at all. 

```
SET(MAN_COMPRESSION "gzip" CACHE STRING "Manpages compression tool")
```

**Comment by orestisfl** [comment]
`cmake -DCOMPRESS_EXECUTABLE=no` can work as a workaround without source code modifications but I am not sure how it works

**Comment by grwlf** [comment]
My guess is that some distros compress manpages if they think they were not compressed by the installation procedure. We used `xz` compressor which is not very popular, so some distros 'fixed' the 'missing' compression by running additional `gzip` round. I changed default compressor to a more recognizable `gz`.
