### ISSUE TITLE
Add option to print layouts in uppercase

### ISSUE THREAD

**Issue by fpaskali** [grwlf/xkb-switch#49]
It would be nice if there is an option to print the layouts in uppercase, as it looks better on some panels and status bars.

I made a modification of longwait function which transforms the string characters to uppercase.

```
if(m_lwait_u) {
  while(true) {
    xkb.wait_event();
    xkb.build_layout(syms);
    syms_collected = true;
    string su = syms.at(xkb.get_group());
    transform(su.begin(), su.end(), su.begin(), ::toupper); 
    cout << su << endl;
  }
}
```

**Comment by grwlf** [comment]
Hi. I think this issue should be solve outside xkb-switch to keep things more unix-way. Did you consider

```
$ xkb-switch | tr [:lower:] [:upper:]
```

?

**Comment by fpaskali** [comment]
I didn't. But it works perfect. Thanks
