### ISSUE TITLE
Recent releases missing from github?

### ISSUE THREAD

**Issue by orestisfl** [grwlf/xkb-switch#57]
Hello,

I notice that the github releases page (currently 1.6.0) does not follow the version numbers from the git (1.8.5). Are you not planning to use the release feature of github anymore?

**Comment by grwlf** [comment]
Hi. No, I do plan to use GitHub release feature, but it looks like some automation stopped working. Thanks for letting me know.

**Comment by grwlf** [comment]
I created 1.8.5 release
