### ISSUE TITLE
Manpage error: ignoring bogus filename

### ISSUE THREAD

**Issue by MatejaMaric** [grwlf/xkb-switch#58]
If I build and install this program from source I get the following error when running `man xkb-switch.1`:

      man: warning: /usr/local/man/man1/xkb-switch.1.gzip: ignoring bogus filename

I will make a pull request to fix this issue.

**Comment by grwlf** [comment]
This seems to be an old story, here are some related issues
https://github.com/grwlf/xkb-switch/issues/48
https://github.com/grwlf/xkb-switch/issues/51

**Comment by grwlf** [comment]
Should be fixed in master, please check
