### ISSUE TITLE
Can MIT license be used instead of GPL?

### ISSUE THREAD

**Issue by sharkov63** [grwlf/xkb-switch#69]
GPL is too strict of a license for some purposes: many companies disallow using any GPL open-source libraries. I would like to create in the future a derived project, and I would like to use MIT license for it. But GPL does not allow to do such thing (I would have to use GPL). Is there any possibility for xkb-switch to switch to a less strict license?

**Comment by grwlf** [comment]
I see no reasons to stick to GPL any more in this project, so I can update the license. @sharkov63 is it still interesting for you?

**Comment by sharkov63** [comment]
> I see no reasons to stick to GPL any more in this project, so I can update the license. @sharkov63 is it still interesting for you?

Yes very much, it would be great if you update to MIT 👍🏻

**Comment by grwlf** [comment]
Should be changed now, please check.

**Comment by sharkov63** [comment]
Thank you! Although as a nitpick, there is still GPL heading text in all sources and headers, for example https://github.com/grwlf/xkb-switch/blob/f829234e8cb99d5225406067df7dd85581c84f21/src/XKbSwitchApi.cpp#L7-L10 I think we can remove it

**Comment by grwlf** [comment]
Done, thanks.

**Comment by sharkov63** [comment]
Thank you very much! 👍🏻
